# Generated by Django 2.2.13 on 2020-08-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passworld',
            new_name='password',
        ),
    ]
