# Generated by Django 2.2.13 on 2020-08-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sign', '0005_auto_20200826_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desciption',
            field=models.CharField(default='简爱', max_length=10),
        ),
    ]
